<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>ColorConverter9</RootNamespace>
    <AssemblyName>ColorConverter9</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColorConverter9.Model\ColorConverter9.Model.csproj" />
  </ItemGroup>

</Project>
